services:
  backend:
    build: ./Back-End
    container_name: quizai-backend
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./Back-End/.env

  frontend:
    build: ./src
    container_name: quizai-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    depends_on:
      - backend